project:
  type: book
  output-dir: _handbook

book:
  title: "seystats: Curating Seychelles data and statistics from publicly-available sources"
  subtitle: Technical Handbook
  author:
    - name: Dr Proochista Ariana
      orcid: 0000-0002-0154-2237
      affiliation: 
        - name: Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine, University of Oxford
          city: Oxford
    - name: Dr Aronrag Meeyai
      affiliation: 
        - name: Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine, University of Oxford
          city: Oxford
    - name: Dr Sylvie Pool
      affiliation:
        - name: Ministry of Health, Seychelles and University of Oxford
    - name: Dr Sanjeev Pugazhendhi
      affiliation:
        - name: Ministry of Health, Seychelles
    - name: Dr Ituen Williams-Umanah
      affiliation:
        - name: Ministry of Health, Seychelles
    - name: Ned Rosalie
      affiliation:
        - name: Ministry of Health, Seychelles
    - name: Keddy Woodcock
      affiliation:
        - name: Ministry of Health, Seychelles
    - name: Ernest Guevarra
      orcid: 0000-0002-4887-4415
      email: ernest@guevarra.io
      affiliation: 
        - name: Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine, University of Oxford
          city: Oxford
  date: last-modified
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    # - part: Data
    #   chapters:
    #     - 01-sources.qmd
    #     - 02-dictionary.qmd
    # - part: Workflow
    #   chapters:
    #     - 03-.qmd
    #     - 06-informed-consent.qmd
    #     - 07-paper-data-collection.qmd
    #     - 08-electronic-data-collection.qmd
    # - part: Community
    #   chapters:
    #     - 09-survey-instrument.qmd
    #     - 10-data-pipeline.qmd
    #     - 11-analysis-workflow.qmd
    - references.qmd
  # appendices: 
  #   - 12-mobile-device-setup.qmd
  #   - 13-odk-setup.qmd
  cover-image: images/seystats.jpeg
  search: true
  repo-url: https://github.com/OxfordIHTM/seystats-handbook/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  google-analytics: 
    tracking-id: ""
    anonymize-ip: true

crossref:
  appendix-title: Appendix
  appendix-delim: ":"

bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: zephyr
    highlight-style: breeze
  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-depth: 3
    highlight-style: breeze
    include-in-header: 
      text: |
        \usepackage{imakeidx}
        \makeindex[intoc=true, columns=2, columnseprule=true]
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/coat_of_arms_of_seychelles.png
    toc: true
    toc-depth: 3
    highlight-style: breeze