---
engine: knitr
---

# Preface {.unnumbered}

In 2022, the **Seychelles-Oxford Partnership** on research capacity building leveraged the vast research experience and skills of University of Oxford research partners for training and upskilling data analysts from the Ministry of Health (MOH) Seychelles.

From this process, the partnership identified that while the Seychelles is one of the few sub-Saharan African countries with efficient, accurate, and comprehensive data collection and disaggregation across a variety of sectors and across a variety of metrics, most of this data are not in the format, shape, and structure that are ready for analysis. A good amount of these rich data are still on paper or ledgers. For the data that are electronic, they are either stored/distributed in formats that are not readily readable by machines for analysis (e.g., portable document format or PDF) or are in proprietary spreadsheet format (i.e. Microsoft Excel) structured into presentational tables meant for reports rather than for actual analysis.

It is from this context that the initial ideas and motivation around this project began. The partnership involves mostly individuals whose roles and responsibilities were related to health. As such, ad hoc plans prioritised health-related data. During this time, rough and informal plans were drawn as to how the various steps will be implemented and how the different technologies required will be resourced. Alongside these, ongoing capacity-building on data management and analysis related to research continued within the partnership.

By 2025, three years on from the start of the partnership, very little has progressed and has been implemented from these informal, ad hoc plans whilst the partnership continued to more research capacity-building focusing on other types of research skills (e.g. qualitative research), on student placement projects for University of Oxford Masters students, and other research efforts (e.g. cancer screening, cancer awareness, cancer quality-of-care). During this period and in all these activities, the same challenges and issues related to data identified in 2022 keep propping up.

It is within this background that the `seystats` project is being (re-)launched. The current motivation is to try to get moving in a more productive direction on the ideas generated in 2022 and to be able to demonstrate the stated advantages of data that is accessible, persistent, and machine-readable/machine-actionable to catalysing research efforts in Seychelles.